[project]
name = "algo-trading-strategy-macd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "ta>=0.11.0",
    "yfinance>=0.2.65",
]
